Repository a8901053/Survive.io, pull requests merged in 2020-09, with the labels that each got.

#28 GameLoop is completed
  client/src/main/java/tw/waterball/survive/io/client/controller/EventController.java
  client/src/main/java/tw/waterball/survive/io/client/controller/SpriteContainer.java
  client/src/main/java/tw/waterball/survive/io/client/gameloop/GameLoop.java
  client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
  client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
  git
Labels: Frontend, development

#34 Update issue template
  .github/ISSUE_TEMPLATE/survive-io-deafult-issue-template.md
Labels: enhancement

#36 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#27 complete StandardGameView class function of playAudioEffect.
  client/src/main/java/tw/waterball/survive/io/client/controller/EventController.java
  client/src/main/java/tw/waterball/survive/io/client/controller/PlayerController.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/GunSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/WeaponSprite.java
  client/src/main/java/tw/waterball/survive/io/client/utils/PlayAudioUtil.java
  client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
  client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
Labels: Frontend, development

#38 Scan whole module of classes by package name
  protocol/src/main/java/tw/waterball/survive/io/protocol/scanner/ModuleClassesScannerUtil.java
Labels: enhancement

#57 Delete the "sprite", "gameloop" and "prototypefactory" package of "client" module.
  client/pom.xml
  client/src/main/java/tw/waterball/survive/io/client/controller/EventController.java
  client/src/main/java/tw/waterball/survive/io/client/controller/PlayerController.java
  client/src/main/java/tw/waterball/survive/io/client/controller/SpriteContainer.java
  client/src/main/java/tw/waterball/survive/io/client/gameloop/GameLoop.java
  client/src/main/java/tw/waterball/survive/io/client/prototypefactory/SpriteName.java
  client/src/main/java/tw/waterball/survive/io/client/prototypefactory/SpritePrototypeFactory.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/Sprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/role/MonsterSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/role/PlayerSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/role/RoleSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/terrain/TerrainSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/DroppedWeaponSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/GunSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/MagazineSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/WeaponSlotSprite.java
  client/src/main/java/tw/waterball/survive/io/client/sprite/weapon/WeaponSprite.java
  client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
  client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
Labels: Frontend, Misc

#65 Implement GameLoop to update sprites and call game listener to render at a fixed time.
  client/pom.xml
  client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
  client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
  game/src/main/java/tw/waterball/survive/io/game/gameloop/GameLoop.java
  game/src/main/java/tw/waterball/survive/io/game/world/GameLoop.java
  game/src/main/java/tw/waterball/survive/io/game/world/SpriteContainer.java
Labels: Game Domain, development

#72 Create the "commons" module.
  .idea/compiler.xml
  commons/pom.xml
  commons/src/main/java/tw/waterball/survive/io/commons/utils/StringUtils.java
  pom.xml
Labels: Misc

#74 JFrame / JPanel canvas implementation
  .drone.yml
  client/src/main/java/tw/waterball/survive/io/client/controller/EventController.java
  client/src/main/java/tw/waterball/survive/io/client/controller/PlayerController.java
  client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
  client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
  game/src/main/java/tw/waterball/survive/io/game/sprite/role/Role.java
  interpreter/pom.xml
Labels: Frontend, development
